[package]
name = "mfek-ipc"
version = "0.0.0"
authors = ["Fredrick Brennan <copypaste@kittens.ph>"]
description = "Modular Font Editor K (MFEK) inter-process communication library."
edition = "2018"

[dependencies]
# Logging
log = "0.4.11"
